const baseCollegeOptions = [
    "Aligarh Muslim University",
    "Alliance University",
    "Amity University",
    "Amity University Haryana, Gurgaon",
    "Amrita Vishwa Vidyapeetham",
    "Anna University",
    "Army Institute of Law",
    "Atal Bihari Vajpayee Indian Institute of Information Technology and Management",
    "Babasheb Bhimrao Ambedkar University",
    "Banaras Hindu University",
    "Bharathidasan Institute of Management",
    "Birla Institute of Management Technology",
    "Birla Institute of Technology",
    "BML Munjal University",
    "Central University of Punjab",
    "Central University of South Bihar",
    "Chanakya National Law University",
    "Chandigarh University",
    "Chitkara University",
    "Christ University",
    "Cochin University of Science and Technology",
    "Dr. B. R. Ambedkar College of Law",
    "Dr. Ram Manohar Lohiya National Law University, Lucknow",
    "Fore School of Management",
    "Galgotias University",
    "Gandhi Institute of Technology And Management (GITAM)",
    "Goa Institute of Management",
    "Graphic Era University",
    "Great Lakes Institute of Management",
    "Gujarat National Law University",
    "Guru Gobind Singh Indraprastha University",
    "Himachal Pradesh National Law University, Shimla",
    "ICFAI Foundation for Higher Education, Hyderabad",
    "IMI Bhubaneswar",
    "IMI Delhi",
    "IMI Kolkata",
    "Indian Institute of Foreign Trade",
    "Indian Institute of Management",
    "Indian Institute of Management Ahmedabad",
    "Indian Institute of Management Bangalore",
    "Indian Institute of Management Bodh Gaya",
    "Indian Institute of Management Calcutta",
    "Indian Institute of Management Indore",
    "Indian Institute of Management Kashipur",
    "Indian Institute of Management Kozhikode",
    "Indian Institute of Management Lucknow",
    "Indian Institute of Management Raipur",
    "Indian Institute of Management Ranchi",
    "Indian Institute of Management Rohtak",
    "Indian Institute of Management Sambalpur",
    "Indian Institute of Management Shillong",
    "Indian Institute of Management Sirmaur",
    "Indian Institute of Management Tiruchirappalli",
    "Indian Institute of Management Udaipur",
    "Indian Institute of Management Visakhapatnam",
    "Indian Institute of Management, Amritsar",
    "Indian Institute of Management, Mumbai",
    "Indian Institute of Technology (Indian School of Mines)",
    "Indian Institute of Technology Bombay",
    "Indian Institute of Technology Delhi",
    "Indian Institute of Technology Jodhpur",
    "Indian Institute of Technology Kanpur",
    "Indian Institute of Technology Kharagpur",
    "Indian Institute of Technology Madras",
    "Indian Institute of Technology Roorkee",
    "Institute of Management Technology",
    "Institute of Management Technology, Nagpur",
    "Institute of Rural Management Anand",
    "Jagan Institute of Management Studies",
    "Jain university,Bangalore",
    "Jaipuria Institute of Management",
    "Jaipuria Institute of Management, Lucknow",
    "Jamia Hamdard",
    "Jamia Millia Islamia",
    "K.J.Somaiya Institute of Management",
    "Kalinga Institute of Industrial Technology",
    "Koneru Lakshmaiah Education Foundation University (K L College of Engineering)",
    "Lovely Professional University",
    "Loyola Institute of Business Administration",
    "Madan Mohan Malaviya University of Technology",
    "Maharashtra National Law University, Nagpur",
    "Malaviya National Institute of Technology",
    "Management Development Institute",
    "Manipal University Jaipur",
    "MICA",
    "Nalsar University of Law",
    "National Institute of Agricultural Extension Management",
    "National Institute of Technology Calicut",
    "National Institute of Technology Tiruchirappalli",
    "National Law Institute University, Bhopal",
    "National Law School of India University",
    "National Law University",
    "National Law University and Judicial Academy",
    "National University of Study \u0026 Research in Law, Ranchi",
    "New Delhi Institute of Management",
    "Nirma University",
    "Pandit Deendayal Energy University",
    "Panjab University",
    "Prin. L.N. Welingkar Institute of Management Development and Research (PGDM)",
    "PSG College of Technology",
    "Rajagiri Business School",
    "S. P. Jain Institute of Management and Research",
    "S.R.M. Institute of Science and Technology",
    "Saveetha Institute of Medical and Technical Sciences",
    "Shanmugha Arts Science Technology \u0026 Research Academy",
    "Siksha \u0027O\u0027 Anusandhan",
    "SVKM\u0027s Narsee Monjee Institute of Management Studies",
    "Symbiosis Institute of Business Management",
    "Symbiosis Law School, Pune",
    "T. A. Pai Management Institute Manipal",
    "Thapar Institute of Engineering and Technology (Deemed-to-be-university)",
    "The West Bengal National University of Juridical Sciences",
    "Thiagarajar School of Management",
    "University of Lucknow",
    "UPES",
    "XIM University",
    "XLRI - Xavier School of Management"
]

const medicalCollegeOptions = [
    "All India Institute of Medical Sciences, Delhi",
    "All India Institute of Medical Sciences Rishikesh",
    "All India Institute of Medical Sciences Bhubaneswar",
    "All India Institute of Medical Sciences Jodhpur",
    "All India Institute of Medical Sciences Bhopal",
    "All India Institute of Medical Sciences Patna",
    "All India Institute of Medical Sciences Raipur",
    "Post Graduate Institute of Medical Education and Research",
    "Christian Medical College",
    "Christian Medical College, Brown Road, Ludhiana",
    "Jawaharlal Institute of Post Graduate Medical Education & Research",
    "Sanjay Gandhi Postgraduate Institute of Medical Sciences",
    "National Institute of Mental Health & Neuro Sciences, Bangalore",
    "King George's Medical University",
    "Kasturba Medical College, Manipal",
    "Kasturba Medical College, Mangalore",
    "Madras Medical College & Government General Hospital, Chennai",
    "Sree Chitra Tirunal Institute for Medical Sciences and Technology, Thiruvananthapuram",
    "Datta Meghe Institute of Higher Education and Research",
    "Sri Ramachandra Institute of Higher Education and Research",
    "Vardhman Mahavir Medical College & Safdarjung Hospital",
    "Institute of Post Graduate Medical Education & Research",
    "Maulana Azad Medical College",
    "Institute of Liver and Biliary Sciences",
    "St. John's Medical College",
    "Lady Hardinge Medical College",
    "Govt. Medical College & Hospital",
    "Dayanand Medical College",
    "JSS Medical College, Mysore",
    "University College of Medical Sciences",
    "Sawai Man Singh Medical College",
    "Medical College",
    "Mahatma Gandhi Medical College and Research Institute",
    "PSG Institute of Medical Sciences and Research",
    "Gujarat Cancer & Research Institute",
    "B. J. Medical College",
    "Jawaharlal Nehru Medical College",
    "Osmania Medical College",
    "Chettinad Academy of Research and Education",
    "M. S. Ramaiah Medical College"
]

export const collegeOptions = [...new Set([...baseCollegeOptions, ...medicalCollegeOptions])].sort((a, b) =>
    a.localeCompare(b),
)

